[build]
  publish = "dist"
  command = "npm install --force --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200